
{
  stack: undefined,
  level: 'error',
  message: 'Internal Server Error',
  timestamp: '2020-09-29T17:35:07.054Z'
}
error: Internal Server Error {"source":"error-handler.middleware.ts","timestamp":"2020-10-01T11:26:23.783Z"}
error: Internal Server Error {"source":"error-handler.middleware.ts","timestamp":"2020-10-01T11:27:04.721Z"}
error: Internal Server Error {"source":"error-handler.middleware.ts","timestamp":"2020-10-01T11:38:32.248Z"}
error: UserController.getById no user here... {"stack":"Error: no user here...\n    at UserService.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:33:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","timestamp":"2020-10-01T13:52:17.525Z"}
error: Internal Server Error {"source":"error-handler.middleware.ts","stack":"Error: no user here...\n    at UserService.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:33:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","timestamp":"2020-10-01T13:52:17.526Z"}
error: UserController.getById {"timestamp":"2020-10-01T13:52:59.573Z"}
error: Internal Server Error {"source":"error-handler.middleware.ts","stack":"Error: no user here...\n    at UserService.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:33:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","timestamp":"2020-10-01T13:52:59.577Z"}
error: UserController.getById {"timestamp":"2020-10-01T13:53:46.948Z"}
error: UserController.getById {"timestamp":"2020-10-01T14:05:45.780Z"}
error: Internal Server Error {"source":"error-handler.middleware.ts","stack":"Error: no user here...\n    at UserService.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:33:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","timestamp":"2020-10-01T14:05:45.785Z"}
error: UserController.getById {"timestamp":"2020-10-01T14:05:48.344Z"}
error: Internal Server Error {"source":"error-handler.middleware.ts","stack":"Error: no user here...\n    at UserService.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:33:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","timestamp":"2020-10-01T14:05:48.345Z"}
error: UserController.getById {"timestamp":"2020-10-01T14:05:49.516Z"}
error: Internal Server Error {"source":"error-handler.middleware.ts","stack":"Error: no user here...\n    at UserService.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:33:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","timestamp":"2020-10-01T14:05:49.517Z"}
error: UserController.getById {"timestamp":"2020-10-01T14:05:50.755Z"}
error: Internal Server Error {"source":"error-handler.middleware.ts","stack":"Error: no user here...\n    at UserService.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:33:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","timestamp":"2020-10-01T14:05:50.756Z"}
error: UserController.getById {"timestamp":"2020-10-01T14:05:51.956Z"}
error: Internal Server Error {"source":"error-handler.middleware.ts","stack":"Error: no user here...\n    at UserService.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:33:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","timestamp":"2020-10-01T14:05:51.957Z"}
error: UserController.getById {"timestamp":"2020-10-01T14:05:56.662Z"}
error: Internal Server Error {"source":"error-handler.middleware.ts","stack":"Error: no user here...\n    at UserService.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:33:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","timestamp":"2020-10-01T14:05:56.663Z"}
error: UserController.getById {"timestamp":"2020-10-01T14:06:48.901Z"}
error: Internal Server Error {"source":"error-handler.middleware.ts","stack":"Error: no user here...\n    at UserService.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:33:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","timestamp":"2020-10-01T14:06:48.906Z"}
error: no user here... {"timestamp":"2020-10-01T14:44:27.734Z"}
error: Internal Server Error {"source":"error-handler.middleware.ts","stack":"Error: no user here...\n    at UserService.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:33:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","timestamp":"2020-10-01T14:44:27.739Z"}
error: Internal Server Error {"source":"error-handler.middleware.ts","stack":"Error: no user here...\n    at UserService.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:33:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","timestamp":"2020-10-01T14:51:28.044Z"}
error: Internal Server Error {"stack":"Error: no user here...\n    at UserService.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:32:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\services\\user.service.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","timestamp":"2020-10-01T15:25:42.300Z"}
error: Internal Server Error {"stack":"ValidationError: Auto-suggest validation error\n    at C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:18:18\n    at Generator.next (<anonymous>)\n    at C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:4:12)\n    at autoSuggest (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:24:16)\n    at Layer.handle [as handle_request] (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at exports.requestLoggerMiddleware (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\middlewares\\request-logger.middleware.ts:10:5)\n    at Layer.handle [as handle_request] (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\layer.js:95:5)","timestamp":"2020-10-03T15:12:18.862Z"}
error: Internal Server Error {"stack":"ValidationError: Auto-suggest validation error\n    at C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:18:18\n    at Generator.next (<anonymous>)\n    at C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:4:12)\n    at autoSuggest (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:24:16)\n    at Layer.handle [as handle_request] (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at exports.requestLoggerMiddleware (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\middlewares\\request-logger.middleware.ts:10:5)\n    at Layer.handle [as handle_request] (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\layer.js:95:5)","timestamp":"2020-10-03T15:23:39.370Z"}
error: Validation Error {"error":{"name":"ValidationError","errors":[{"keyword":"type","dataPath":"/limit","schemaPath":"#/properties/limit/type","params":{"type":"number"},"message":"should be number"}]},"timestamp":"2020-10-03T15:29:34.135Z"}
error: Validation Error {"error":{"name":"ValidationError","errors":[{"keyword":"type","dataPath":"/limit","schemaPath":"#/properties/limit/type","params":{"type":"number"},"message":"should be number"}]},"body":{"limit":"2"},"timestamp":"2020-10-03T15:30:44.951Z"}
error: Validation Error {"error":{"name":"ValidationError","errors":[{"keyword":"type","dataPath":"/limit","schemaPath":"#/properties/limit/type","params":{"type":"number"},"message":"should be number"}]},"arguments":{},"body":{"limit":"2"},"timestamp":"2020-10-03T16:23:42.902Z"}
error: Validation Error {"error":{"name":"ValidationError","errors":[{"keyword":"type","dataPath":"/limit","schemaPath":"#/properties/limit/type","params":{"type":"number"},"message":"should be number"}],"status":400},"arguments":{},"body":{"limit":"2"},"timestamp":"2020-10-03T16:32:39.886Z"}
error: Validation Error {"error":{"name":"ValidationError","errors":[{"keyword":"type","dataPath":"/limit","schemaPath":"#/properties/limit/type","params":{"type":"number"},"message":"should be number"}],"status":400},"arguments":{},"body":{"limit":"2"},"timestamp":"2020-10-03T16:33:35.079Z"}
error: ValidationError {"error":{"name":"ValidationError","errors":[{"keyword":"type","dataPath":"/limit","schemaPath":"#/properties/limit/type","params":{"type":"number"},"message":"should be number"}],"status":400},"arguments":{},"body":{"limit":"2"},"timestamp":"2020-10-03T16:35:59.657Z"}
error: ValidationError:Auto-suggest validation error {"error":{"name":"ValidationError","errors":[{"keyword":"type","dataPath":"/limit","schemaPath":"#/properties/limit/type","params":{"type":"number"},"message":"should be number"}],"status":400},"arguments":{},"body":{"limit":"2"},"timestamp":"2020-10-03T16:38:14.451Z"}
error: ValidationError: {"error":{"name":"ValidationError","errors":[{"keyword":"type","dataPath":"/limit","schemaPath":"#/properties/limit/type","params":{"type":"number"},"message":"should be number"}],"status":400},"arguments":{},"body":{"limit":"2"},"timestamp":"2020-10-03T16:39:54.765Z"}
error: ValidationError: {"error":{"name":"ValidationError","error":[{"keyword":"type","dataPath":"/limit","schemaPath":"#/properties/limit/type","params":{"type":"number"},"message":"should be number"}],"status":400},"arguments":{},"body":{"limit":"2"},"timestamp":"2020-10-03T16:44:09.930Z"}
error: ValidationError: {"stack":"ValidationError: \n    at C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:16:18\n    at Generator.next (<anonymous>)\n    at C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:4:12)\n    at autoSuggest (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:24:16)\n    at Layer.handle [as handle_request] (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at exports.requestLoggerMiddleware (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\middlewares\\request-logger.middleware.ts:10:5)\n    at Layer.handle [as handle_request] (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\layer.js:95:5)","error":{"name":"ValidationError","error":[{"keyword":"type","dataPath":"/limit","schemaPath":"#/properties/limit/type","params":{"type":"number"},"message":"should be number"}],"status":400},"arguments":{},"body":{"limit":"2"},"timestamp":"2020-10-03T16:47:20.874Z"}
error: ValidationError: {"stack":"ValidationError: \n    at C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:16:18\n    at Generator.next (<anonymous>)\n    at C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:4:12)\n    at autoSuggest (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:24:16)\n    at Layer.handle [as handle_request] (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at exports.requestLoggerMiddleware (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\middlewares\\request-logger.middleware.ts:10:5)\n    at Layer.handle [as handle_request] (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\layer.js:95:5)","error":[{"keyword":"type","dataPath":"/limit","schemaPath":"#/properties/limit/type","params":{"type":"number"},"message":"should be number"}],"arguments":{},"body":{"limit":"2"},"timestamp":"2020-10-03T16:49:22.329Z"}
error: ValidationError: {"stack":"ValidationError: \n    at C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:27:18\n    at Generator.next (<anonymous>)\n    at C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:4:12)\n    at update (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:34:16)\n    at Layer.handle [as handle_request] (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at next (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\route.js:131:14)\n    at Route.dispatch (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\route.js:112:3)","error":[{"keyword":"type","dataPath":"/login","schemaPath":"#/properties/login/type","params":{"type":"string"},"message":"should be string"}],"arguments":{},"body":{"login":5},"timestamp":"2020-10-03T16:53:50.907Z"}
error: ValidationError:Update User {"error":[{"keyword":"type","dataPath":"/login","schemaPath":"#/properties/login/type","params":{"type":"string"},"message":"should be string"}],"stack":"ValidationError: Update User\n    at C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:27:18\n    at Generator.next (<anonymous>)\n    at C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:4:12)\n    at update (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:34:16)\n    at Layer.handle [as handle_request] (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at next (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\route.js:131:14)\n    at Route.dispatch (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\route.js:112:3)","arguments":{},"body":{"login":5},"timestamp":"2020-10-03T16:56:24.014Z"}
error: ValidationError:UserGroup addUserToGroup {"error":{"error":{"_original":{"login":5},"details":[{"message":"\"users\" is required","path":["users"],"type":"any.required","context":{"label":"users","key":"users"}}]}},"stack":"ValidationError: UserGroup addUserToGroup\n    at C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user-groups\\user-group.validator.ts:12:18\n    at Generator.next (<anonymous>)\n    at C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user-groups\\user-group.validator.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user-groups\\user-group.validator.ts:4:12)\n    at addUsersToGroup (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user-groups\\user-group.validator.ts:17:16)\n    at Layer.handle [as handle_request] (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at exports.requestLoggerMiddleware (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\middlewares\\request-logger.middleware.ts:10:5)\n    at Layer.handle [as handle_request] (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\layer.js:95:5)","arguments":{},"body":{"login":5},"timestamp":"2020-10-03T17:49:46.142Z"}
error: Internal Server Error {"stack":"NotFoundError: User 11 not found\n    at UserRepository.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:34:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","timestamp":"2020-10-03T18:01:36.524Z"}
error: Internal Server Error {"stack":"NotFoundError: User 11 not found\n    at UserRepository.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:34:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","timestamp":"2020-10-03T18:02:10.356Z"}
error: Internal Server Error {"stack":"NotFoundError: User 11 not found\n    at UserRepository.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:34:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","timestamp":"2020-10-03T18:03:36.213Z"}
error: Internal Server Error {"stack":"NotFoundError: User 11 not found\n    at UserRepository.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:34:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","timestamp":"2020-10-03T18:04:04.973Z"}
error: NotFoundError:User 11 not found {"stack":"NotFoundError: User 11 not found\n    at UserRepository.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:34:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","arguments":{},"body":{},"timestamp":"2020-10-03T18:06:44.199Z"}
error: NotFoundError:User 11 not found {"stack":"NotFoundError: User 11 not found\n    at UserRepository.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:34:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","arguments":{},"body":{},"timestamp":"2020-10-03T18:07:15.209Z"}
error: NotFoundError:User 11 not found {"stack":"NotFoundError: User 11 not found\n    at UserRepository.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:34:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","arguments":{},"body":{},"timestamp":"2020-10-03T18:18:09.448Z"}
error: NotFoundError:User 11 not found {"stack":"NotFoundError: User 11 not found\n    at UserRepository.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:34:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","arguments":{},"body":{},"timestamp":"2020-10-03T18:20:27.657Z"}
error: NotFoundError:User 11 not found {"stack":"NotFoundError: User 11 not found\n    at UserRepository.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:34:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","arguments":{},"body":{},"timestamp":"2020-10-03T18:21:01.477Z"}
error: NotFoundError:Route not found {"stack":"NotFoundError: Route not found\n    at C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\api\\routes\\not-found.routes.ts:6:14\n    at Layer.handle [as handle_request] (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\index.js:281:22\n    at param (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\index.js:354:14)\n    at param (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\index.js:365:14)\n    at Function.process_params (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\index.js:410:3)\n    at next (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\index.js:275:10)","arguments":{},"body":{},"timestamp":"2020-10-03T18:25:07.413Z"}
error: ValidationError:User update {"error":[{"keyword":"type","dataPath":"/login","schemaPath":"#/properties/login/type","params":{"type":"string"},"message":"should be string"}],"stack":"ValidationError: User update\n    at C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:27:18\n    at Generator.next (<anonymous>)\n    at C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:4:12)\n    at update (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\validators\\user\\user.validator.ts:34:16)\n    at Layer.handle [as handle_request] (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at next (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\route.js:131:14)\n    at Route.dispatch (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\route.js:112:3)","arguments":{},"body":{"login":5},"timestamp":"2020-10-03T19:09:01.618Z"}
error: NotFoundError:User 11 not found {"stack":"NotFoundError: User 11 not found\n    at UserRepository.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:60:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","arguments":{},"body":{"login":"111"},"timestamp":"2020-10-03T19:09:14.237Z"}
error: NotFoundError:Route not found {"stack":"NotFoundError: Route not found\n    at C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\api\\routes\\not-found.routes.ts:6:14\n    at Layer.handle [as handle_request] (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\index.js:281:22\n    at param (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\index.js:354:14)\n    at param (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\index.js:365:14)\n    at Function.process_params (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\index.js:410:3)\n    at next (C:\\Projects\\Node_js_mentoring\\node_modules\\express\\lib\\router\\index.js:275:10)","arguments":{},"body":{},"timestamp":"2020-10-05T08:59:09.190Z"}
error: Unhandled Promise Rejection {"error":{"name":"NotFoundError","status":404},"timestamp":"2020-10-05T09:02:36.318Z"}
error: NotFoundError:User 21 not found {"stack":"NotFoundError: User 21 not found\n    at UserRepository.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:33:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","arguments":{},"body":{},"timestamp":"2020-10-05T09:03:33.219Z"}
error: NotFoundError:User 21 not found {"stack":"NotFoundError: User 21 not found\n    at UserRepository.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:33:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","arguments":{},"body":{},"timestamp":"2020-10-05T09:03:34.995Z"}
error: NotFoundError:User 21 not found {"stack":"NotFoundError: User 21 not found\n    at UserRepository.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:33:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","arguments":{},"body":{},"timestamp":"2020-10-05T09:03:39.838Z"}
error: Unhandled Promise Rejection {"error":{"name":"NotFoundError","status":404},"timestamp":"2020-10-05T09:03:54.028Z"}
error: Unhandled Promise Rejection {"error":{"name":"NotFoundError","status":404},"timestamp":"2020-10-05T09:04:49.010Z"}
error: Unhandled Promise Rejection {"error":{"name":"NotFoundError","status":404},"timestamp":"2020-10-05T09:13:39.536Z"}
error: NotFoundError:User 21 not found {"stack":"NotFoundError: User 21 not found\n    at UserRepository.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:33:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","arguments":{},"body":{},"timestamp":"2020-10-05T09:17:52.524Z"}
error: uncaughtException {"timestamp":"2020-10-05T11:36:33.003Z"}
error: uncaughtException {"error":{"code":"EACCES","errno":"EACCES","syscall":"listen","address":"PORT","port":-1},"timestamp":"2020-10-05T11:37:56.590Z"}
error: Unhandled Promise Rejection {"error":{"name":"NotFoundError","status":404},"timestamp":"2020-10-05T12:31:18.950Z"}
error: Unhandled Promise Rejection {"error":{"name":"NotFoundError","status":404},"timestamp":"2020-10-05T12:55:34.886Z"}
error: Unhandled Promise Rejection {"error":{"name":"NotFoundError","status":404},"timestamp":"2020-10-05T12:56:53.262Z"}
error: Unhandled Promise Rejection {"error":{"name":"NotFoundError","status":404},"timestamp":"2020-10-05T12:57:04.491Z"}
error: Unhandled Promise Rejection {"error":{"name":"NotFoundError","status":404},"timestamp":"2020-10-05T12:57:11.871Z"}
error: Unhandled Promise Rejection {"error":{"name":"NotFoundError","status":404},"timestamp":"2020-10-05T12:57:26.424Z"}
error: NotFoundError:User 21 not found {"stack":"NotFoundError: User 21 not found\n    at UserRepository.<anonymous> (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:33:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Projects\\Node_js_mentoring\\src\\module2\\task1\\repositories\\user.repository.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","arguments":{},"body":{},"timestamp":"2020-10-05T13:01:59.677Z"}
